cost/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('budget', views.BudgetListView.as_view(), name='budget_list'),
    path('budget/<int:year>', views.BudgetListView.as_view(), name='budget_list'),
    path('budget/add', views.BudgetCreateView.as_view(), name='budget_create'),
    path('budget/update/<int:pk>',
         views.BudgetUpdateView.as_view(), name='budget_update'),
    path('budget/detail/<int:pk>',
         views.BudgetDetailView.as_view(), name='budget_detail'),
    path('budget/ajax/load_budget', views.load_budgets, name='load_budget'),

    path('pay', views.PayListView.as_view(), name='pay_list'),
    path('mypay', views.MyPayListView.as_view(), name='mypay_list'),
    path('pay/update/<int:pk>', views.PayUpdateView.as_view(), name='pay_update'),
    path('pay/add', views.PayCreateView.as_view(), name='pay_create'),
    path('pay/add/<int:project_id>',
         views.PayCreateView.as_view(), name='pay_create_fromproject'),
    path('pay/search', views.PaySearchView.as_view(), name='pay_search'),
    path('pay/exportpays', views.export_pays, name='export_pays')
    #  path('pay', views.gridnode),

]

projects/urls.py
from django.urls import path, include

from . import views
from . import views_ajax

urlpatterns = [

    path('add', views.ProjectCreateView.as_view(), name='project_create'),
    path('add/<int:parentpk>', views.ProjectCreateView.as_view(),
         name='project_create'),
    path('detail/<int:pk>', views.ProjectDetailView.as_view(), name='project_detail'),
    path('update/<int:pk>', views.ProjectUpdateView.as_view(), name='project_update'),
    path('search', views.ProjectSearchView.as_view(), name='project_search'),

    path('ajax/load_projects', views_ajax.load_projects, name='load_project'),
    path('ajax/load_tasks_fin_dep',
         views_ajax.load_tasks_dayfin_to_dep, name='load_tasks_dayfin_dep'),
    path('ajax/load_tasks_fin',
         views_ajax.load_tasks_dayfin, name='load_tasks_dayfin'),
    path('ajax/load_tasks_fin/<int:u_id>',
         views_ajax.load_tasksto_dayfin, name='load_tasksto_dayfin'),

    path('schedule/exportschedules',
         views.export_schedules, name='export_schedules'),
    path('exportprojects', views.export_projects, name='export_projects'),

    path('schedules', views.ScheduleListView.as_view(), name='schedule_list'),
    path('myschedules', views.MyScheduleListView.as_view(), name='myschedule_list'),
    path('schedules/search', views.ScheduleSearchView.as_view(),
         name='schedule_search'),
    path('<int:project_id>/addschedule',
         views.ScheduleCreateView.as_view(), name='schedule_create'),
    path('schedule/detail/<int:pk>',
         views.ScheduleDetailView.as_view(), name='schedule_detail'),
    path('schedule/update/<int:pk>',
         views.ScheduleUpdateView.as_view(), name='schedule_update'),
    path('my/', views.MyProjectListView.as_view(), name='myproject_list'),
    path('my/<slug:state>/<slug:main>',
         views.MyProjectListView.as_view(), name='myproject_list'),
    path('<slug:state>/<slug:main>',
         views.ProjectListView.as_view(), name='project_list'),
    path('', views.ProjectListView.as_view(), name='project_list'),




]

somsys/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cost/', include('cost.urls')),
    path('projects/', include('projects.urls')),
    path('accounts/', include('accounts.urls')),
    path('kanban/', include('kanban.urls')),
    path('', include('projects.urls')),
    path('comments/', include('django_comments.urls')),

]

projects/models.py
from django.db import models
import django.utils.timezone as timezone
# from django.utils.timezone import now
from django.contrib.auth import get_user_model
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db.models.signals import post_save
from django.dispatch import receiver
from cost.models import Pay
from django.db.models import Sum

# Create your models here.

User = get_user_model()


class Project(models.Model):

    BUSINESSENTITY_CHOICES = (
        (u'集团', u'集团'),
        (u'管委会', u'管委会')
    )

    TASK_STATE_CHOICES = (
        (u'前期', u'前期'),
        (u'设计', u'设计'),
        (u'招标', u'招标'),
        (u'合同流程', u'合同流程'),
        (u'实施', u'实施'),
        (u'验收完成', u'验收完成'),
        (u'完成', u'完成'),
        (u'暂停', u'暂停'),
        (u'其他', u'其他')
    )

    name = models.CharField(max_length=128, verbose_name='项目名')
    businessentity = models.CharField(
        max_length=6, choices=BUSINESSENTITY_CHOICES, default='集团', verbose_name='主体')
    task_state = models.CharField(
        max_length=20, choices=TASK_STATE_CHOICES, default='其他', verbose_name='状态')
  #  transactor = models.CharField(max_length=32, verbose_name='经办人')
    transactor = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='transactor_projects', blank=True, null=True, verbose_name='经办人')
    amount = models.DecimalField(
        max_digits=11, decimal_places=2, verbose_name='金额', default=0)
    content = models.TextField(blank=True, verbose_name='内容简介')
    cdate = models.DateTimeField(default=timezone.now, verbose_name='创建日期')
    lcdate = models.DateTimeField(auto_now=True, verbose_name='修改日期')
    remark = models.CharField(max_length=256, blank=True, verbose_name='备注')

    cuser = models.ForeignKey(
        User, on_delete=models.SET_NULL, related_name='create_projects', blank=True, null=True, verbose_name='创建人')
    lcuser = models.ForeignKey(
        User, on_delete=models.SET_NULL, related_name='change_projects', blank=True, null=True, verbose_name='最后修改人')

    parent_project = models.ForeignKey(
        'Project', on_delete=models.SET_NULL, related_name='child_projects', blank=True, null=True, verbose_name='父项目')

    department = models.ForeignKey(
        "accounts.Structure", on_delete=models.CASCADE, related_name='projects', verbose_name="部门")

    def __str__(self):
        return self.name

    def unpaid(self):
        allamount = self.pays.all().aggregate(Sum('amount'))
        return self.amount - (allamount['amount__sum'] or 0)

    def isexpired(self):
        isexpired = False
        for schedule in self.schedules.all():
            if schedule.is_expired():
                isexpired = True
                break
        return isexpired

    def progress(self):
        progress = self.schedules.filter(isfin=True).aggregate(Sum('progress'))
        return progress['progress__sum'] or 0


class Schedule(models.Model):

    TASK_TYPE_CHOICES = (
        (u'进度', u'进度'),
        (u'付款', u'付款'),
        (u'会议', u'会议'),
        (u'流程', u'流程'),
        (u'发文', u'发文'),
        (u'招采审核', u'招采审核'),
        (u'方案评审会', u'方案评审会'),
        (u'其他', u'其他')
    )

    name = models.CharField(max_length=128, verbose_name='事项')
    cdate = models.DateTimeField(default=timezone.now, verbose_name='创建日期')
    lcdate = models.DateTimeField(auto_now=True, verbose_name='修改日期')

    task_type = models.CharField(
        max_length=20, choices=TASK_TYPE_CHOICES, null=True, verbose_name='类型')

    # transactor = models.CharField(max_length=32, verbose_name='经办人')
    transactor = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='transactor_schedules', blank=True, null=True, verbose_name='经办人')
    content = models.TextField(blank=True, verbose_name='内容')

    iskey = models.BooleanField(default=False, verbose_name=u'是否关键节点')
    isfin = models.BooleanField(default=False, verbose_name=u'是否完成')
    progress = models.IntegerField(default=0, validators=[MaxValueValidator(
        100), MinValueValidator(0)], verbose_name=u'进度占比')

    deadline = models.DateTimeField(null=True, verbose_name='截止日期')

    remark = models.CharField(max_length=256, blank=True, verbose_name='备注')

    cuser = models.ForeignKey(
        User, on_delete=models.SET_NULL, related_name='create_schedules', blank=True, null=True, verbose_name='')
    lcuser = models.ForeignKey(
        User, on_delete=models.SET_NULL, related_name='change_schedules', blank=True, null=True, verbose_name='')

    project = models.ForeignKey(
        'Project', on_delete=models.CASCADE, related_name='schedules', verbose_name='')

    department = models.ForeignKey(
        "accounts.Structure", on_delete=models.CASCADE, verbose_name="部门")

    def is_expired(self):
        if self.deadline:
            if not self.isfin and timezone.now() > self.deadline:
                return True
        return False

    def __str__(self):
        return self.name


@receiver(post_save, sender=Schedule)
def change_schedule(sender, instance, created, **kwargs):
    if instance:
        project = instance.project
        project.lcdate = timezone.now
        project.save()


@receiver(post_save, sender=Project)
def change_project(sender, instance, created, **kwargs):
    if instance:
        project = instance.parent_project
        lv = 1
        while project:
            project.lcdate = timezone.now
            project.save()
            project = project.parent_project
            lv = lv+1
            if lv > 4:
                break

projects/forms.py
from django.db import models
from django import forms
from django.forms import ModelForm
from .models import Project, Schedule


class ProjectForm(ModelForm):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(ProjectForm, self).__init__(*args, **kwargs)
        for filed in self.fields.values():
            filed.widget.attrs.update({'class': 'form-control'})

        self.fields["parent_project"].queryset = Project.objects.filter(
            department=self.user.department)

    class Meta:
        model = Project
        fields = ['name', 'businessentity', 'task_state', 'content', 'amount',
                  'transactor', 'parent_project', 'remark', 'lcuser']

        labels = {
            'name': '项目名',
            'businessentity': '单位主体',
            'task_state': '状态',
            'amount': '金额',
            'content': '内容',
            'remark': '备注',
            'transactor': '经办人',
            'parent_project': '父项目',
        }
        widgets = {'lcuser': forms.HiddenInput()}


class DateInput(forms.DateInput):
    input_type = 'date'


class ScheduleForm(ModelForm):
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(ScheduleForm, self).__init__(*args, **kwargs)

        # for filed in self.fields.values():
        #   filed.widget.attrs.update({'class': 'form-control'})
        self.fields['project'].disabled = True
        self.fields['project'].widget.attrs.update({"class": "form-control"})
        self.fields['name'].widget.attrs.update({"class": "form-control"})
        self.fields['task_type'].widget.attrs.update({"class": "form-control"})
        self.fields['transactor'].widget.attrs.update(
            {"class": "form-control"})
        # self.fields['isfin'].widget.attrs.update(
        #    {"class": "form-control"})
        self.fields['progress'].widget.attrs.update(
            {"class": "form-control"})
        self.fields['content'].widget.attrs.update({"class": "form-control"})
        self.fields['remark'].widget.attrs.update({"class": "form-control"})

        self.fields["project"].queryset = Project.objects.filter(
            department=self.user.department)

    class Meta:
        model = Schedule
        fields = ['project', 'name', 'task_type', 'transactor', 'iskey', 'isfin', 'progress', 'deadline',
                  'content', 'remark', 'lcuser']
        widgets = {
            'deadline': DateInput(),
        }

        labels = {
            'name': '事项',
            'task_type': '类型',
            'remark': '备注',
            'transactor': '经办人',
            'project': '项目',
            'content': '内容',
        }
        widgets = {'lcuser': forms.HiddenInput()}

templates/projects/project_create.html
{% extends "projects/project_base.html" %}
{% load static %}
{% block content %}
<h2 class="page-title">
    项目创建
  </h2>
<div class="m-5 col-sm-6 col-lg-8">
    <form action="{% url 'project_create' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-primary m-1" type="submit" value="新增">

    </form>
</div>
{% endblock %}


{% block addjs %}


<link href="{% static 'plugins/select2/select2.min.css' %}" rel="stylesheet" />
<script src="{% static 'plugins/select2/select2.min.js' %}"></script>

<script>
    var $j = jQuery.noConflict();
    $j('#id_parent_project').select2({
        ajax: {
            url: '{% url 'load_project' %}',
            dataType: 'json',
            delay: 250,
            data: function (params) {
                return {
                    q: params.term, // search term
                    page: params.page
                };
            },
            processResults: function (data, params) {
                params.page = params.page || 1;
                // Transforms the top-level key of the response object from 'items' to 'results'
                console.log(data)
                return {
                    results: data.results,
                    pagination: {
                        more: (params.page * 30) < data.total_count
                    }
                };
            },
        },
        placeholder: '搜索项',
        allowClear : true, // 允许清空
        minimumInputLength: 1,
    });


</script>


{% endblock %}

templates/projects/project_detail.html
{% extends "projects/project_base.html" %}
{% load getitem_tag %}
{% load static %}
{% load comments %}
{% block content %}
<h2 class="page-title">
    项目明细
  </h2>
<div class="m-5 col-sm-10 col-lg-10">
    <div class="col-sm-6 col-lg-10">
        <h2>{{ project.name }}</h2>
        <p>父项目：
            {% if project.parent_project %}
            <a href="{% url 'project_detail' project.parent_project.id %}">{{ project.parent_project }}</a>
            {% else %}
            无
            {% endif %}
        </p>
        <table class="table">
            <tr>
                <td>经办人：{{ project.transactor }}</td>
                <td>单位主体：{{ project.businessentity }}</td>
            </tr>
            <tr>
                <td>创建日期：{{ project.cdate|date:"Y-m-d" }}</td>
                <td>修改日期：{{ project.lcdate|date:"Y-m-d" }}</td>
            </tr>
            <tr>
                <td>金额：{{ project.amount|div:10000 }}万</td>
                <td>进度：<progress max="100" value="{{ progress }}" titile="{{ progress }}%"></progress></td>
            </tr>
            <tr>
                <td colspan="2">
                    <p>内容：</p>
                    <p class="px-3">{{ project.content }}</p>
                </td>
            </tr>
        </table>
        <p><a href="{% url 'project_update' project.id%}">编辑</a></p>
    </div>

    <div>
        <div>
            <span style="font-size:x-large">子项目</span><a class="btn btn-primary m-1"
                href="{% url 'project_create' project.id %}" role="button">添加</a>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">项目名</th>
                    <th scope="col">活动日期</th>
                    <th scope="col">经办人</th>
                    <th scope="col">状态</th>
                    <th scope="col">金额</th>
                    <th scope="col">进度</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for cproject in project.child_projects.all|dictsortreversed:"lcdate" %}
                <tr>
                    <td><a href="{% url 'project_detail' cproject.id%}">{{ cproject.name }}</a></td>
                    <td>{{ cproject.lcdate| date:"Y-m-d" }}</td>
                    <td>{{ cproject.transactor }}</td>
                    <td>{{ cproject.task_state }}</td>
                    <td>{{ cproject.amount|div:10000 }}万</td>
                    <td><progress  max="100" value="{{ cprogresses|get_item:cproject.id }}"
                            titile="{{ cprogresses|get_item:cproject.id }}%"></progress></td>
                    <td><a href="{% url 'project_update' cproject.id%}">修改</a></td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="3">空</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <div>
        <div>
            <span style="font-size:x-large">支付</span>
            <a class="btn btn-primary m-1"
                href="{% url 'pay_create_fromproject' project.id %}" role="button">添加</a>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">支付项</th>
                    <th scope="col">支付日期</th>
                    <th scope="col">经办人</th>
                    <th scope="col">金额</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for pay in project.pays.all|dictsortreversed:"paydate" %}
                <tr>
                    <td>{{ pay.name }}</td>
                    <td>{{ pay.paydate|date:"Y-m-d" }}</td>
                    <td>{{ pay.transactor }}</td>
                    <td>{{ pay.amount|div:10000 }}万</td>
                    <td><a href="{% url 'pay_update' pay.id%}">编辑</a></td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="4">空</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <div>
        <div>
            <span style="font-size:x-large">进程</span><a class="btn btn-primary m-1"
                href="{% url 'schedule_create' project.id %}" role="button">添加</a>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">事件</th>
                    <th scope="col">日期</th>
                    <th scope="col">经办人</th>
                    <th scope="col">关键节点</th>
                    <th scope="col">是否完成</th>
                    <th scope="col">进度占比</th>
                    <th scope="col">超期否</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for schedule in project.schedules.all|dictsortreversed:"lcdate" %}
                <tr {% if sexpireds|get_item:schedule.id %}style="color:red" {% endif %}>
                    <td><a href="{% url 'schedule_detail' schedule.id%}">{{ schedule.name }}</a></td>
                    <td>{{ schedule.lcdate| date:"Y-m-d" }}</td>
                    <td>{{ schedule.transactor }}</td>
                    <td><input type="checkbox" onclick="return false" {% if schedule.iskey %}checked{% endif %} /></td>
                    <td><input type="checkbox" onclick="return false" {% if schedule.isfin %}checked{% endif %} /></td>
                    <td>{{ schedule.progress }}</td>
                    <td>{% if sexpireds|get_item:schedule.id %}<span class="badge bg-danger">超期</span>
                        {% else %}<span class="badge bg-success">未超期</span>{% endif %}</td>
                    <td><a href="{% url 'schedule_update' schedule.id%}">修改</a></td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="3">空</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h4>评论列表</h4>
        </div>
     
        <div class="panel-body">
            {% get_comment_list for project as comments %}
            {% for comment in comments %}
                <div class="blog_comment" name="F{{comment.id}}">
                    <p class="comment_title">
                        #{{ comment.submit_date|date:"Y-m-d H:i"}} @ {{ comment.user_name }}：
                    </p>
                    
                    <p class="comment_content">{{ comment.comment }}</p>
                </div>            
            {% empty %}
                <span>暂无评论</span>
            {% endfor %}
        </div>

        {% get_comment_form for project as form %}
        <form action="{% comment_form_target %}" method="POST">
        {% csrf_token %}
        <input type="hidden" id="id_name" name="name" value="{{ user.realname }}" />
        <input type="hidden" id="id_email" name="email" value="xx@xx.com" />
           
        {{ form.comment }}
        {{ form.content_type }}
        {{ form.object_pk }}
        {{ form.timestamp }}
        {{ form.security_hash }}
        <input type="hidden" name="next" value="{% url 'project_detail' project.id %}" />
        <input type="submit" value="提交评论" id="id_submit" />
        </form>
       
    </div>

</div>
{% endblock %}

templates/projects/project_list.html
{% extends "projects/project_base.html" %}
{% load getitem_tag %}
{% load static %}
{% block content %}
<h2 class="page-title">
    项目列表
  </h2>
<div class="col-md-6">
    <table>
        <tr>
            <td> 
                <select class="form-control" onchange="self.location.href=options[selectedIndex].value">
                    <option value="{% url 'project_list' %}all/{{ ismain }}" {% if state == "all" %} selected {% endif %}>全部</option>
                    <option value="{% url 'project_list' %}fin/{{ ismain }}" {% if state == "fin" %}selected{% endif %}>
                        已完成</option>
                    <option value="{% url 'project_list' %}unfin/{{ ismain }}" {% if state == "unfin" %}selected{% endif %}>未完成
                    </option>
                </select>
            </td>
            <td>
                <select class="form-control" onchange="self.location.href=options[selectedIndex].value">
                    <option value="{% url 'project_list' %}{{ state }}/0" {% if ismain == '0' %} selected {% endif %}>
                        所有项目</option>
                    <option value="{% url 'project_list' %}{{ state }}/1" {% if ismain != '0' %} selected {% endif %}>
                        主要项目</option>
                </select>
            </td>
            <td>
                <a class="btn btn-primary m-1" href="{% url 'project_create' %}" role="button">添加</a>
            </td>
            <td>
                <a class="btn btn-primary m-1" href="{% url 'export_projects' %}?state={{ state }}&main={{ main }}" role="button">导出</a>
            </td>
        </tr>
    </table>
</div>
<div>
    {% include "projects/projects_comp.html" %}
</div>
{% if is_paginated %}
{% include "common/paginated.html"  %}
{% endif %}

{% endblock %}

templates/projects/project_my_list.html
{% extends "projects/project_base.html" %}
{% load getitem_tag %}
{% load static %}
{% block content %}
<h2 class="page-title">
    项目列表
  </h2>
<div class="col-md-6">
    <table>
        <tr>
            <td> 
                <select class="form-control" onchange="self.location.href=options[selectedIndex].value">
                    <option value="{% url 'myproject_list' %}all/{{ ismain }}" {% if state == "all" %} selected {% endif %}>全部</option>
                    <option value="{% url 'myproject_list' %}fin/{{ ismain }}" {% if state == "fin" %}selected{% endif %}>
                        已完成</option>
                    <option value="{% url 'myproject_list' %}unfin/{{ ismain }}" {% if state == "unfin" %}selected{% endif %}>未完成
                    </option>
                </select>
            </td>
            <td>
                <select class="form-control" onchange="self.location.href=options[selectedIndex].value">
                    <option value="{% url 'myproject_list' %}{{ state }}/0" {% if ismain == '0' %} selected {% endif %}>
                        所有项目</option>
                    <option value="{% url 'myproject_list' %}{{ state }}/1" {% if ismain != '0' %} selected {% endif %}>
                        主要项目</option>
                </select>
            </td>
            <td>
                <a class="btn btn-primary m-1" href="{% url 'project_create' %}" role="button">添加</a>
            </td>
            <td>
              
            </td>
        </tr>
    </table>
</div>
<div>
    {% include "projects/projects_comp.html" %}
</div>
{% if is_paginated %}
{% include "common/paginated.html"  %}
{% endif %}

{% endblock %}

templates/projects/project_search.html
{% extends "projects/project_base.html" %}
{% load getitem_tag %}
{% load static %}
{% block content %}
<h2 class="page-title">
    项目搜索
  </h2>

<div>
    {% include "projects/projects_comp.html" %}
</div>

{% endblock %}

templates/projects/schedule_base.html
{% extends "projects/project_base.html" %}
{% load static %}

{% block searchurl %}
{% url 'schedule_search' %}
{% endblock %}

templates/projects/schedule_create.html
{% extends "projects/schedule_base.html" %}
{% load static %}
{% block content %}
<h2 class="page-title">
    任务创建
  </h2>
<div class="m-5 col-sm-6 col-lg-8">
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-primary m-1" type="submit" value="新增">

    </form>
</div>



{% endblock %}

{% block addjs %}
<link rel="stylesheet" href="{% static 'plugins/datetimepicker/jquery.datetimepicker.min.css' %}" />
<script src="{% static 'plugins/datetimepicker/jquery.datetimepicker.full.min.js' %}"></script>
<script>
    var $j = jQuery.noConflict();
    $j(function () {
        $j('#id_deadline').datetimepicker({
            format: 'Y-m-d H:i'
        });
        $j.datetimepicker.setLocale('zh');
    });
</script>
{% endblock %}

templates/projects/schedule_detail.html
{% extends "projects/schedule_base.html" %}
{% load static %}
{% load comments %}
{% block content %}
<h2 class="page-title">
    任务明细
  </h2>

<div class="m-5 col-sm-8 col-lg-8">
    <h1>任务：{{ schedule.name }}</h1>
    <h2 class="form-control">项目：{{ schedule.project }}</h2>
    <table class="table">
        <tr>
            <td>类型：{{ schedule.task_type }}</td>
            <td>经办人：{{ schedule.transactor }}</td>
        </tr>
        <tr>
            <td>创建日期：{{ schedule.cdate|date:"Y-m-d" }}</td>
            <td>截止时间：{{ schedule.deadline }}</td>
        </tr>
        <tr>
            <td>是否完成：<input type="checkbox" onclick="return false" {% if schedule.isfin %}checked{% endif %} /></td>
            <td>关键节点：<input type="checkbox" onclick="return false" {% if schedule.iskey %}checked{% endif %} /></td>
        </tr>
        <tr>
            <td>进度值：{{ schedule.progress }}</td>
            <td>超期否：{% if sexpired %}超期{% else %}未超期{% endif %}</td>
        </tr>
        <tr>
            <td colspan="2"><p>内容：</p><p>{{ schedule.content }}</p></td>
        </tr>
        <tr>
            <td colspan="2">备注：{{ schedule.remark }}</td>
        </tr>
    </table>
    <p><a href="{% url 'schedule_update' schedule.id%}">编辑</a></p>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4>评论列表</h4>
        </div>
      
        <div class="panel-body">
            {% get_comment_list for schedule as comments %}
            {% for comment in comments %}
                <div class="blog_comment" name="F{{comment.id}}">
                    <p class="comment_title">
                        #{{ comment.submit_date|date:"Y-m-d H:i"}} @ {{ comment.user_name }}：
                    </p>
                    
                    <p class="comment_content">{{ comment.comment }}</p>
                </div>            
            {% empty %}
                <span>暂无评论</span>
            {% endfor %}
        </div>
      
        {% get_comment_form for schedule as form %}
        <form action="{% comment_form_target %}" method="POST">
        {% csrf_token %}
        <input type="hidden" id="id_name" name="name" value="{{ user.realname }}" />
        <input type="hidden" id="id_email" name="email" value="xx@xx.com" />
           
        {{ form.comment }}
        {{ form.content_type }}
        {{ form.object_pk }}
        {{ form.timestamp }}
        {{ form.security_hash }}
        <input type="hidden" name="next" value="{% url 'schedule_detail' schedule.id %}" />
        <input type="submit" value="提交评论" id="id_submit" />
        </form>
       
      </div>
</div>


{% endblock %}

templates/projects/schedule_update.html
{% extends "projects/schedule_base.html" %}
{% load static %}
{% block content %}
<h2 class="page-title">
    任务修改
  </h2>
<div class="m-5 col-sm-6 col-lg-8">
    <form action="{% url 'schedule_update' schedule.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-primary m-1" type="submit" value="更新" />
    </form>
</div>
{% endblock %}

{% block addjs %}
<link rel="stylesheet" href="{% static 'plugins/datetimepicker/jquery.datetimepicker.min.css' %}" />
<script src="{% static 'plugins/datetimepicker/jquery.datetimepicker.full.min.js' %}"></script>
<script>
    var $j = jQuery.noConflict();
    $j(function () {
        $j('#id_deadline').datetimepicker({
            format: 'Y-m-d H:i'
        });
        $j.datetimepicker.setLocale('zh');
    });
</script>
{% endblock %}