cost/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('budget', views.BudgetListView.as_view(), name='budget_list'),
    path('budget/<int:year>', views.BudgetListView.as_view(), name='budget_list'),
    path('budget/add', views.BudgetCreateView.as_view(), name='budget_create'),
    path('budget/update/<int:pk>',
         views.BudgetUpdateView.as_view(), name='budget_update'),
    path('budget/detail/<int:pk>',
         views.BudgetDetailView.as_view(), name='budget_detail'),
    path('budget/ajax/load_budget', views.load_budgets, name='load_budget'),

    path('pay', views.PayListView.as_view(), name='pay_list'),
    path('mypay', views.MyPayListView.as_view(), name='mypay_list'),
    path('pay/update/<int:pk>', views.PayUpdateView.as_view(), name='pay_update'),
    path('pay/add', views.PayCreateView.as_view(), name='pay_create'),
    path('pay/add/<int:project_id>',
         views.PayCreateView.as_view(), name='pay_create_fromproject'),
    path('pay/search', views.PaySearchView.as_view(), name='pay_search'),
    path('pay/exportpays', views.export_pays, name='export_pays')
    #  path('pay', views.gridnode),

]

somsys/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cost/', include('cost.urls')),
    path('projects/', include('projects.urls')),
    path('accounts/', include('accounts.urls')),
    path('kanban/', include('kanban.urls')),
    path('', include('projects.urls')),
    path('comments/', include('django_comments.urls')),

]

cost/models.py
from django.db import models
import django.utils.timezone as timezone
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.


class BudgetYear(models.Model):
    year = models.DecimalField(max_digits=4, unique=True, decimal_places=0)

    def __str__(self):
        return str(self.year)

    def __repr__(self):
        return str(self.year)


class Budget(models.Model):

    BUSINESSENTITY_CHOICES = (
        (u'集团', u'集团'),
        (u'管委会', u'管委会')
    )

    name = models.CharField(max_length=128)
    businessentity = models.CharField(
        max_length=6, choices=BUSINESSENTITY_CHOICES, default=u'集团')
    amount = models.DecimalField(max_digits=11, decimal_places=2)
    cdate = models.DateTimeField(default=timezone.now)
    lcdate = models.DateTimeField(auto_now=True)
    remark = models.CharField(max_length=256, blank=True)

    cuser = models.ForeignKey('accounts.OAUser', on_delete=models.SET_NULL,
                              related_name='create_budgets', blank=True, null=True)
    lcuser = models.ForeignKey('accounts.OAUser', on_delete=models.SET_NULL,
                               related_name='change_budgets', blank=True, null=True)

    year = models.ForeignKey('BudgetYear', on_delete=models.SET_NULL,
                             related_name='budgets', blank=True, null=True)

    department = models.ForeignKey(
        "accounts.Structure", on_delete=models.CASCADE, related_name='budgets', verbose_name="部门")

    def __str__(self):
        return repr(self.year)+'-'+self.businessentity+'-'+self.name

    def __repr__(self):
        return repr(self.year)+'-'+self.businessentity+'-'+self.name


class Pay(models.Model):

    BUSINESSENTITY_CHOICES = (
        (u'集团', u'集团'),
        (u'管委会', u'管委会')
    )

    name = models.CharField(max_length=128)
    businessentity = models.CharField(
        max_length=6, choices=BUSINESSENTITY_CHOICES)
    paydate = models.DateTimeField(default=timezone.now)
    # transactor = models.CharField(max_length=32)
    transactor = models.ForeignKey(
        'accounts.OAUser', on_delete=models.CASCADE, related_name='transactor_pays', blank=True, null=True, verbose_name='经办人')

    amount = models.DecimalField(max_digits=11, decimal_places=2)
    remark = models.CharField(max_length=256, blank=True)

    cuser = models.ForeignKey(
        'accounts.OAUser', on_delete=models.SET_NULL, related_name='create_pays', blank=True, null=True)
    lcuser = models.ForeignKey(
        'accounts.OAUser', on_delete=models.SET_NULL, related_name='change_pays', blank=True, null=True)

    project = models.ForeignKey(
        'projects.Project', on_delete=models.SET_NULL, related_name='pays', blank=True, null=True)
    budget = models.ForeignKey(
        'Budget', on_delete=models.SET_NULL, related_name='pays', blank=True, null=True)

    department = models.ForeignKey(
        "accounts.Structure", on_delete=models.CASCADE, related_name='pays', verbose_name="部门")

    def __str__(self):
        return self.name

# pay change or add, update project change time


@receiver(post_save, sender=Pay)
def change_schedule(sender, instance, created, **kwargs):
    if instance:
        project = instance.project
        if project:
            project.lcdate = timezone.now
            project.save()

cost/forms.py
from django.db import models

from django import forms
from django.forms import widgets, ModelForm, ModelChoiceField, HiddenInput
from django.forms import ModelForm
from .models import Budget, BudgetYear, Pay
from accounts.models import OAUser, Structure
from projects.models import Project


class BudgetForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(BudgetForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({"class": "form-control"})
        self.fields['businessentity'].widget.attrs.update(
            {"class": "form-control"})
        self.fields['year'].widget.attrs.update({"class": "form-control"})
        self.fields['amount'].widget.attrs.update({"class": "form-control"})
        self.fields['remark'].widget.attrs.update({"class": "form-control"})

    class Meta:
        model = Budget
        fields = ['name', 'businessentity',
                  'year', 'amount', 'remark', 'lcuser']

        labels = {
            'name': '预算项',
            'businessentity': '单位主体',
            'year': '预算年',
            'amount': '金额',
            'remark': '备注'
        }
        widgets = {'lcuser': HiddenInput()}


class PayForm(ModelForm):
    budgetyear = ModelChoiceField(
        label="预算年", queryset=BudgetYear.objects.all())

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(PayForm, self).__init__(*args, **kwargs)
        project = self.initial.get('project')

        self.fields['name'].widget.attrs.update({"class": "form-control"})
        self.fields['businessentity'].widget.attrs.update(
            {"class": "form-control"})
        self.fields['paydate'].widget.attrs.update({"class": "form-control"})
        self.fields['transactor'].widget.attrs.update(
            {"class": "form-control"})
        self.fields['amount'].widget.attrs.update({"class": "form-control"})
        self.fields['budgetyear'].widget.attrs.update(
            {"class": "form-control"})
        self.fields['budget'].widget.attrs.update({"class": "form-control"})

        self.fields['project'].widget.attrs.update({"class": "form-control"})

        self.fields['remark'].widget.attrs.update({"class": "form-control"})

        self.fields["project"].queryset = Project.objects.none()
        self.fields['budget'].queryset = Budget.objects.none()
     #   if 'project' in self.data:
        self.fields["project"].queryset = Project.objects.all()  # filter(
        #     department=self.user.department)

        if 'budgetyear' in self.data:
            try:
                yearid = int(self.data.get('budgetyear'))
                self.fields['budget'].queryset = Budget.objects.filter(
                    year_id=yearid)
            except (ValueError, TypeError):
                pass

        budgetid = self.initial.get('budget')

        if budgetid is not None:
            budget = Budget.objects.get(pk=budgetid)
            #self.budgetyear = budget.year
            self.initial['budgetyear'] = budget.year
            self.fields['budget'].queryset = Budget.objects.filter(
                year=budget.year)

    class Meta:
        model = Pay
        fields = ['name', 'businessentity', 'paydate', 'transactor',
                  'amount', 'budgetyear', 'budget', 'project', 'remark', 'lcuser']

        labels = {
            'name': '支付项',
            'businessentity': '单位主体',
            'paydate': '支付时间',
            'transactor': '经办人',
            'amount': '金额',
            'budget': '预算',
            'project': '项目',
            'remark': '备注'
        }

        widgets = {'lcuser': HiddenInput()}

cost/views.py
import logging
from audioop import reverse
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.views.generic import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from accounts.models import Structure, OAUser
from projects.models import Project
from .models import Budget, Pay, BudgetYear
from .forms import BudgetForm, PayForm
from django.db.models import Sum
from django.db.models import Q
import datetime
import csv

# Create your views here.

# logger = logging.getLogger(__name__)


@login_required
def load_budgets(request):
    user = request.user
    year_id = request.GET.get('yearid')
    budgets = Budget.objects.filter(
        Q(year_id=year_id), Q(department=user.department))
    return render(request, 'cost/budget_dropdown_list_options.html', {'budgets': budgets})


class BudgetListView(LoginRequiredMixin, ListView):
    template_name = 'cost/budget_list.html'
    model = Budget
    context_object_name = 'budget_list'

    def get(self, request, *args, **kwargs):
        year = self.kwargs.get('year')
        if year == None:
            nowyear = datetime.datetime.now().strftime('%Y')
            return HttpResponseRedirect(reverse_lazy('budget_list', kwargs={'year': nowyear}))

        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        user = self.request.user
        y = self.kwargs['year']
        yn = BudgetYear.objects.get(year=y)
        return Budget.objects.filter(year=yn, department=user.department)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # 加入支出统计
        allpay = {}
        for budget in context['budget_list']:
            aa = budget.pays.all().aggregate(Sum('amount'))
            allpay[budget.id] = aa['amount__sum']

        years = [[year.year, reverse('budget_list', kwargs={
                                     'year': year.year}), False] for year in BudgetYear.objects.all()]
        for year in years:
            if year[0] == self.kwargs['year']:
                year[2] = True
                break

        context['years'] = years
        context['allpay'] = allpay

        return context


class BudgetCreateView(LoginRequiredMixin, CreateView):
    template_name = 'cost/budget_create.html'
    model = Budget
    form_class = BudgetForm
    success_url = reverse_lazy('budget_list')

    def get_form_kwargs(self):
        kwargs = super(BudgetCreateView, self).get_form_kwargs()

        kwargs.update(
            {'initial': {'cdate': datetime.date.today(
            ), 'lcdate': datetime.date.today(), 'remark': ''}}
        )
        return kwargs

    def form_valid(self, form):

        user = self.request.user
        budget = form.save(False)
        budget.cuser = user
        budget.lcuser = user
        budget.department = user.department
        budget.save(True)

        # logger.info('add budget-'+budget)
        return HttpResponseRedirect(self.success_url)


class BudgetUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'cost/budget_update.html'
    model = Budget
    form_class = BudgetForm
    context_object_name = 'budget'

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('budget_detail', kwargs={'pk': pk})

    def get_form_kwargs(self):
        kwargs = super(BudgetUpdateView, self).get_form_kwargs()
        user = self.request.user

        kwargs.update(
            {'initial': {'lcuser': user}}
        )
        return kwargs


class BudgetDetailView(LoginRequiredMixin, DetailView):
    template_name = 'cost/budget_detail.html'
    model = Budget
    context_object_name = 'budget'


class PaySearchView(LoginRequiredMixin, ListView):
    template_name = 'cost/pay_search.html'
    model = Pay
    context_object_name = 'pay_list'

    def get_queryset(self):
        user = self.request.user
        new_context = None
        keychar = self.request.GET.get('name', '')
        if keychar != None:
            new_context = Pay.objects.filter(
                Q(department=user.department),
                Q(name__contains=keychar) |
                Q(transactor__realname__contains=keychar)
            ).order_by('-paydate')
        return new_context

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        keychar = self.request.GET.get('name', '')
        context['keychar'] = keychar
        return context


class PayListView(LoginRequiredMixin, ListView):
    template_name = 'cost/pay_list.html'
    model = Pay
    context_object_name = 'pay_list'

    page_type = ''
    paginate_by = 20
    page_kwarg = 'page'
    # ordering = ['-paydate']
    # queryset = Pay.objects.order_by('-paydate')

    @property
    def page_number(self):
        page_kwarg = self.page_kwarg
        page = self.kwargs.get(
            page_kwarg) or self.request.GET.get(page_kwarg) or 1
        return page

    def get_queryset(self):
        user = self.request.user
        new_context = Pay.objects.filter(
            department=user.department).order_by('-paydate')
        return new_context


class MyPayListView(PayListView):
    template_name = 'cost/pay_my_list.html'

    def get_queryset(self):
        user = self.request.user
        return Pay.objects.filter(
            department=user.department, transactor=user).order_by('-paydate')

class PayCreateView(LoginRequiredMixin, CreateView):
    template_name = 'cost/pay_create.html'
    model = Pay
    form_class = PayForm
    success_url = reverse_lazy('pay_list')

    def get_form_kwargs(self):
        kwargs = super(PayCreateView, self).get_form_kwargs()

        project_id = self.kwargs.get('project_id')

        kwargs.update({'user': self.request.user})
        user = self.request.user
        if project_id:
            project = Project.objects.get(id=project_id)
            # 进入网页，该字段值：{'initial': {}, 'prefix': None, 'instance': None}

            kwargs.update(
                # 给表单的phase字段传递外键实例
                {'initial': {'paydate': datetime.date.today(), 'remark': '',
                             'project': project, 'transactor': user}}
            )
        else:
            kwargs.update(
                {'initial': {'paydate': datetime.date.today(), 'remark': '',
                             'transactor': user}}
            )
        return kwargs

    def form_valid(self, form):
        user = self.request.user
        pay = form.save(False)
        pay.cuser = user
        pay.lcuser = user
        pay.department = user.department
        pay.save(True)
        return HttpResponseRedirect(self.success_url)


class PayUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'cost/pay_update.html'
    model = Pay
    form_class = PayForm
    context_object_name = 'pay'
    success_url = reverse_lazy('pay_list')

    def get_form_kwargs(self):
        kwargs = super(PayUpdateView, self).get_form_kwargs()
        user = self.request.user
        kwargs.update({'user': user})
        kwargs.update(
            {'initial': {'lcuser': user}}
        )

        return kwargs


@login_required
def export_pays(request):
    response = HttpResponse(content_type='text/csv')
    response.charset = 'utf-8-sig' if "Windows" in request.headers.get(
        'User-Agent') else 'utf-8'
    response['Content-Disposition'] = 'attachment; filename="pays.csv"'

    writer = csv.writer(response)
    user = request.user
    keychar = request.GET.get('name', '')

    pay_list = Pay.objects.filter(
            department=user.department).order_by('-paydate')
    
    if (keychar != ''):
        pay_list = pay_list.filter(
            Q(name__contains=keychar) |
            Q(transactor__contains=keychar)
            ).order_by('-paydate')

    writer.writerow(['payname', 'businessentity', 'date',
                    'author', 'amount', 'budget', 'project'])
    for pay in pay_list:
        writer.writerow([pay.name, pay.businessentity, str(
            pay.paydate), pay.transactor, pay.amount, pay.budget])

    return response

templates/cost/budget_base.html
{% extends "cost/pay_base.html" %}
{% load static %}

templates/cost/budget_create.html
{% extends "cost/budget_base.html" %}
{% load static %}



{% block content %}

<h2 class="page-title">
    创建预算
  </h2>

<div class="m-5 col-sm-6 col-lg-8">
    <form action="{% url 'budget_create' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-primary m-1" type="submit" value="新增">

    </form>
</div>
{% endblock %}

templates/cost/budget_detail.html
{% extends "cost/budget_base.html" %}
{% load static %}
{% load getitem_tag %}
{% block content %}
<h2 class="page-title">
    预算明细
  </h2>
<div class="m-5 col-sm-6 col-lg-8">
    <h2>{{ budget.name }}</h2>
    <p>单位主体：{{ budget.businessentity }}</p>
    <p>预算年：{{ budget.year }}</p>
    <p>金额：{{ budget.amount|div:10000 }}万</p>
    <p>创建日期：{{ budget.cdate|date:"Y-m-d" }}</p>
    <p>修改日期：{{ budget.lcdate|date:"Y-m-d" }}</p>

    <h3>支出</h3>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">支付项</th>
                <th scope="col">支付日期</th>
                <th scope="col">经办人</th>
                <th scope="col">金额</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            {% for pay in budget.pays.all|dictsortreversed:"paydate" %}
            <tr>
                <td>{{ pay.name }}</td>
                <td>{{ pay.paydate|date:"Y-m-d" }}</td>
                <td>{{ pay.transactor }}</td>
                <td>{{ pay.amount|div:10000 }}万</td>
                <td><a href="{% url 'pay_update' pay.id%}">编辑</a></td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="4">空</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    
</div>
{% endblock %}

templates/cost/budget_dropdown_list_options.html
<option value="">---------</option>
{% for budget in budgets %}
<option value="{{ budget.pk }}">{{ budget }}</option>
{% endfor %}

templates/cost/budget_list.html
{% extends "cost/budget_base.html" %}
{% load getitem_tag %}
{% load static %}


{% block content %}
<h2 class="page-title">
    预算列表
  </h2>
<div>
    <table>
        <tr>
            <td>
    <select class="form-control" onchange="self.location.href=options[selectedIndex].value">
        {% for year in years %}
        {% if year.2 == True %}
        <option value ="{{ year.1 }}" selected>{{ year.0 }}年</option>
        {% else %}
        <option value ="{{ year.1 }}">{{ year.0 }}年</option>
        {% endif %}
        {% endfor %}
    </select></td>
    <td>
    <a class="btn btn-primary m-1" href="{% url 'budget_create' %}" role="button">添加</a></td>
</tr>
    </table>
</div>
<table class="table">
    <thead>
        <tr>
            <th scope="col">预算</th>
            <th scope="col">主体</th>
            <th scope="col">年</th>
            <th scope="col">金额</th>
            <th scope="col">已支</th>
        </tr>
    </thead>
    <tbody>
        {% for budget in budget_list %}
        <tr>
            <td><a href="{% url 'budget_detail' budget.id%}">{{ budget.name }}</a></td>
            <td>{{ budget.businessentity }}</td>
            <td>{{ budget.year }}</td>
            <td>{{ budget.amount|div:10000 }}万</td>
            <td>
                {% if allpay|get_item:budget.id %}
                {{ allpay|get_item:budget.id|div:10000 }}
                {% else %}
                0
                {% endif %}万
            </td>
            <td><a href="{% url 'budget_update' budget.id%}">编辑</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

templates/cost/budget_update.html
{% extends "cost/budget_base.html" %}
{% load static %}
{% block content %}
<h2 class="page-title">
    预算修改
  </h2>
<div class="m-5">
    <form action="{% url 'budget_update' budget.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-primary m-1" type="submit" value="更新" />
    </form>
</div>
{% endblock %}

templates/cost/pay_base.html
{% extends "base.html" %}
{% load static %}


{% block searchurl %}
{% url 'pay_search' %}
{% endblock %}

templates/cost/pay_create.html
{% extends "cost/pay_base.html" %}
{% load static %}
{% block content %}
<h2 class="page-title">
  支出创建
</h2>
<div class="m-5 col-sm-6 col-lg-8">
  <form class="form-line" id="payForm" action="{% url 'pay_create' %}"
    method="post">
    {% csrf_token %}

    {{ form.as_p }}

    <input class="btn btn-primary m-1" type="submit" value="新增">

  </form>
</div>
{% endblock %}

{% block addjs %}


<link href="{% static 'plugins/select2/select2.min.css' %}" rel="stylesheet" />
<script src="{% static 'plugins/select2/select2.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'plugins/datetimepicker/jquery.datetimepicker.min.css' %}" />
<script src="{% static 'plugins/datetimepicker/jquery.datetimepicker.full.min.js' %}"></script>
<script>
    var $j = jQuery.noConflict();
    $j(function () {
        $j('#id_paydate').datetimepicker({
            format: 'Y-m-d H:i'
        });
        $j.datetimepicker.setLocale('zh');
    });

  $j('#id_project').select2({
    ajax: {
      url: '{% url 'load_project' %}',
      dataType: 'json',
      delay: 250,
      data: function (params) {
        return {
          q: params.term, // search term
          page: params.page
        };
      },
      processResults: function (data, params) {
        params.page = params.page || 1;
        // Transforms the top-level key of the response object from 'items' to 'results'
        return {
          results: data.results,
          pagination: {
            more: (params.page * 30) < data.total_count
          }
        };
      },
    },
    placeholder: '搜索项',
    allowClear : true, // 允许清空
    minimumInputLength: 1,
  });



  $j("#id_budgetyear").change(function () {
    var url = "{% url 'load_budget' %}";//$j("#payForm").attr("data-budgets-url");  // 获取 `load_cities` view
    var budgetyearId = $j(this).val();  // 在HTML中获取选取的国家ID
    $j.ajax({                       // 初始化 AJAX 请求
      url: url,                    //设置请求地址(= localhost:8000/hr/ajax/load-cities/)
      data: {
        'yearid': budgetyearId       // countryId传到GET参数
      },
      success: function (data) {   //  视图函数 `load_cities`返回到`data`
        $j("#id_budget").html(data);  // 用返回的数据替换城市输入框的内容
      }
    });
  });
</script>

{% endblock %}

templates/cost/pay_list.html
{% extends "cost/pay_base.html" %}
{% load static %}
{% load getitem_tag %}
{% block content %}
<h2 class="page-title">
    支出列表
  </h2>
<div class="col-md-4">
    <a class="btn btn-primary  m-1" href="{% url 'pay_create' %}" role="button">添加</a>
    <a class="btn btn-primary  m-1" href="{% url 'export_pays' %}" role="button">导出</a>
</div>
<div>
    {% include "cost/pays_comp.html" %}
</div>
{% if is_paginated %}
{% include "common/paginated.html"  %}
{% endif %}

{% endblock %}

templates/cost/pay_my_list.html
{% extends "cost/pay_base.html" %}
{% load static %}
{% load getitem_tag %}
{% block content %}
<h2 class="page-title">
    支出列表
  </h2>
<div class="col-md-4">
    <a class="btn btn-primary  m-1" href="{% url 'pay_create' %}" role="button">添加</a>

</div>
<div>
    {% include "cost/pays_comp.html" %}
</div>
{% if is_paginated %}
{% include "common/paginated.html"  %}
{% endif %}

{% endblock %}

templates/cost/pay_search.html
{% extends "cost/pay_base.html" %}
{% load static %}
{% load getitem_tag %}
{% block content %}
<h2 class="page-title">
    支付搜索
  </h2>
<div class="col-md-4">
<a class="btn btn-primary btn-lg m-1" href="{% url 'export_pays' %}?name={{ keychar }}" role="button">导出</a>
</div>
<div>
    {% include "cost/pays_comp.html" %}
</div>


{% endblock %}

templates/cost/pay_update.html
{% extends "cost/pay_base.html" %}
{% load static %}
{% block content %}
<h2 class="page-title">
    支付修改
  </h2>
<div class="m-5  col-sm-6 col-lg-8">
    <form class="form-line" id="payForm" data-budgets-url="{% url 'load_budget' %}"
        action="{% url 'pay_update' pay.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-primary m-1" type="submit" value="更新" />
    </form>
</div>
{% endblock %}

{% block addjs %}


<link href="{% static 'plugins/select2/select2.min.css' %}" rel="stylesheet" />
<script src="{% static 'plugins/select2/select2.min.js' %}"></script>

<link rel="stylesheet" href="{% static 'plugins/datetimepicker/jquery.datetimepicker.min.css' %}" />
<script src="{% static 'plugins/datetimepicker/jquery.datetimepicker.full.min.js' %}"></script>
<script>
    var $j = jQuery.noConflict();
    $j(function () {
        $j('#id_paydate').datetimepicker({
            format: 'Y-m-d H:i'
        });
        $j.datetimepicker.setLocale('zh');
    });

    $j('#id_project').select2({
        ajax: {
            url: '{% url 'load_project' %}',
            dataType: 'json',
            delay: 250,
            data: function (params) {
                return {
                    q: params.term, // search term
                    page: params.page
                };
            },
            processResults: function (data, params) {
                params.page = params.page || 1;
                // Transforms the top-level key of the response object from 'items' to 'results'
                return {
                    results: data.results,
                    pagination: {
                        more: (params.page * 30) < data.total_count
                    }
                };
            },
        },
        placeholder: '搜索项',
        allowClear : true, // 允许清空
        minimumInputLength: 1,
    });


    $j("#id_budgetyear").change(function () {
        var url = "{% url 'load_budget' %}";//$j("#payForm").attr("data-budgets-url");  // 获取 `load_cities` view
        var budgetyearId = $j(this).val();  // 在HTML中获取选取的国家ID
        $j.ajax({                       // 初始化 AJAX 请求
            url: url,                    //设置请求地址(= localhost:8000/hr/ajax/load-cities/)
            data: {
                'yearid': budgetyearId       // countryId传到GET参数
            },
            success: function (data) {   //  视图函数 `load_cities`返回到`data`
                $j("#id_budget").html(data);  // 用返回的数据替换城市输入框的内容
            }
        });
    });
</script>

{% endblock %}

templates/cost/pays_comp.html
{% load static %}
{% load getitem_tag %}

<table class="table">
    <thead>
        <tr>
            <th scope="col">支付项</th>
            <th scope="col">主体</th>
            <th scope="col">支付日期</th>
            <th scope="col">经办人</th>
            <th scope="col">金额</th>
            <th scope="col">预算</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        {% for pay in pay_list %}
        <tr>
            <td>{{ pay.name }}</td>
            <td>{{ pay.businessentity }}</td>
            <td>{{ pay.paydate|date:"Y-m-d" }}</td>
            <td>{{ pay.transactor }}</td>
            <td>{{ pay.amount|div:10000 }}万</td>
            <td>
                {% if pay.budget %}
                {{ pay.budget }}
                {% endif %}
            </td>
            <td><a href="{% url 'pay_update' pay.id%}">编辑</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>