cost/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('budget', views.BudgetListView.as_view(), name='budget_list'),
    path('budget/<int:year>', views.BudgetListView.as_view(), name='budget_list'),
    path('budget/add', views.BudgetCreateView.as_view(), name='budget_create'),
    path('budget/update/<int:pk>',
         views.BudgetUpdateView.as_view(), name='budget_update'),
    path('budget/detail/<int:pk>',
         views.BudgetDetailView.as_view(), name='budget_detail'),
    path('budget/ajax/load_budget', views.load_budgets, name='load_budget'),

    path('pay', views.PayListView.as_view(), name='pay_list'),
    path('mypay', views.MyPayListView.as_view(), name='mypay_list'),
    path('pay/update/<int:pk>', views.PayUpdateView.as_view(), name='pay_update'),
    path('pay/add', views.PayCreateView.as_view(), name='pay_create'),
    path('pay/add/<int:project_id>',
         views.PayCreateView.as_view(), name='pay_create_fromproject'),
    path('pay/search', views.PaySearchView.as_view(), name='pay_search'),
    path('pay/exportpays', views.export_pays, name='export_pays')
    #  path('pay', views.gridnode),

]

kanban/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.PersonKanbanView.as_view(), name='ukanban'),
    path('<int:u_id>', views.PersonKanbanView.as_view(), name='ukanbanto'),
    path('dep/', views.DepmentKanbanView.as_view(), name='depkanban'),
]

somsys/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cost/', include('cost.urls')),
    path('projects/', include('projects.urls')),
    path('accounts/', include('accounts.urls')),
    path('kanban/', include('kanban.urls')),
    path('', include('projects.urls')),
    path('comments/', include('django_comments.urls')),

]

kanban/models.py
from django.db import models

# Create your models here.

projects/models.py
from django.db import models
import django.utils.timezone as timezone
# from django.utils.timezone import now
from django.contrib.auth import get_user_model
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db.models.signals import post_save
from django.dispatch import receiver
from cost.models import Pay
from django.db.models import Sum

# Create your models here.

User = get_user_model()


class Project(models.Model):

    BUSINESSENTITY_CHOICES = (
        (u'集团', u'集团'),
        (u'管委会', u'管委会')
    )

    TASK_STATE_CHOICES = (
        (u'前期', u'前期'),
        (u'设计', u'设计'),
        (u'招标', u'招标'),
        (u'合同流程', u'合同流程'),
        (u'实施', u'实施'),
        (u'验收完成', u'验收完成'),
        (u'完成', u'完成'),
        (u'暂停', u'暂停'),
        (u'其他', u'其他')
    )

    name = models.CharField(max_length=128, verbose_name='项目名')
    businessentity = models.CharField(
        max_length=6, choices=BUSINESSENTITY_CHOICES, default='集团', verbose_name='主体')
    task_state = models.CharField(
        max_length=20, choices=TASK_STATE_CHOICES, default='其他', verbose_name='状态')
  #  transactor = models.CharField(max_length=32, verbose_name='经办人')
    transactor = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='transactor_projects', blank=True, null=True, verbose_name='经办人')
    amount = models.DecimalField(
        max_digits=11, decimal_places=2, verbose_name='金额', default=0)
    content = models.TextField(blank=True, verbose_name='内容简介')
    cdate = models.DateTimeField(default=timezone.now, verbose_name='创建日期')
    lcdate = models.DateTimeField(auto_now=True, verbose_name='修改日期')
    remark = models.CharField(max_length=256, blank=True, verbose_name='备注')

    cuser = models.ForeignKey(
        User, on_delete=models.SET_NULL, related_name='create_projects', blank=True, null=True, verbose_name='创建人')
    lcuser = models.ForeignKey(
        User, on_delete=models.SET_NULL, related_name='change_projects', blank=True, null=True, verbose_name='最后修改人')

    parent_project = models.ForeignKey(
        'Project', on_delete=models.SET_NULL, related_name='child_projects', blank=True, null=True, verbose_name='父项目')

    department = models.ForeignKey(
        "accounts.Structure", on_delete=models.CASCADE, related_name='projects', verbose_name="部门")

    def __str__(self):
        return self.name

    def unpaid(self):
        allamount = self.pays.all().aggregate(Sum('amount'))
        return self.amount - (allamount['amount__sum'] or 0)

    def isexpired(self):
        isexpired = False
        for schedule in self.schedules.all():
            if schedule.is_expired():
                isexpired = True
                break
        return isexpired

    def progress(self):
        progress = self.schedules.filter(isfin=True).aggregate(Sum('progress'))
        return progress['progress__sum'] or 0


class Schedule(models.Model):

    TASK_TYPE_CHOICES = (
        (u'进度', u'进度'),
        (u'付款', u'付款'),
        (u'会议', u'会议'),
        (u'流程', u'流程'),
        (u'发文', u'发文'),
        (u'招采审核', u'招采审核'),
        (u'方案评审会', u'方案评审会'),
        (u'其他', u'其他')
    )

    name = models.CharField(max_length=128, verbose_name='事项')
    cdate = models.DateTimeField(default=timezone.now, verbose_name='创建日期')
    lcdate = models.DateTimeField(auto_now=True, verbose_name='修改日期')

    task_type = models.CharField(
        max_length=20, choices=TASK_TYPE_CHOICES, null=True, verbose_name='类型')

    # transactor = models.CharField(max_length=32, verbose_name='经办人')
    transactor = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='transactor_schedules', blank=True, null=True, verbose_name='经办人')
    content = models.TextField(blank=True, verbose_name='内容')

    iskey = models.BooleanField(default=False, verbose_name=u'是否关键节点')
    isfin = models.BooleanField(default=False, verbose_name=u'是否完成')
    progress = models.IntegerField(default=0, validators=[MaxValueValidator(
        100), MinValueValidator(0)], verbose_name=u'进度占比')

    deadline = models.DateTimeField(null=True, verbose_name='截止日期')

    remark = models.CharField(max_length=256, blank=True, verbose_name='备注')

    cuser = models.ForeignKey(
        User, on_delete=models.SET_NULL, related_name='create_schedules', blank=True, null=True, verbose_name='')
    lcuser = models.ForeignKey(
        User, on_delete=models.SET_NULL, related_name='change_schedules', blank=True, null=True, verbose_name='')

    project = models.ForeignKey(
        'Project', on_delete=models.CASCADE, related_name='schedules', verbose_name='')

    department = models.ForeignKey(
        "accounts.Structure", on_delete=models.CASCADE, verbose_name="部门")

    def is_expired(self):
        if self.deadline:
            if not self.isfin and timezone.now() > self.deadline:
                return True
        return False

    def __str__(self):
        return self.name


@receiver(post_save, sender=Schedule)
def change_schedule(sender, instance, created, **kwargs):
    if instance:
        project = instance.project
        project.lcdate = timezone.now
        project.save()


@receiver(post_save, sender=Project)
def change_project(sender, instance, created, **kwargs):
    if instance:
        project = instance.parent_project
        lv = 1
        while project:
            project.lcdate = timezone.now
            project.save()
            project = project.parent_project
            lv = lv+1
            if lv > 4:
                break

kanban/views.py
from django.shortcuts import render
from django.conf import settings
from django.views.generic import FormView, RedirectView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView, TemplateView
from projects.models import Project, Schedule
from cost.models import Pay
from django.db.models import Q, Sum
from django.contrib.auth import get_user_model


User = get_user_model()

# Create your views here.


class PersonKanbanView(LoginRequiredMixin, TemplateView):
    template_name = 'kanban/personto.html'

    def get_projects(self, user: User):
        return Project.objects.filter(
            Q(department=user.department),
            Q(transactor=user))

    def get_schedules(self, user: User):
        return Schedule.objects.filter(
            Q(department=user.department),
            Q(transactor=user))

    def get_pays(self, user: User):
        return Pay.objects.filter(
            Q(department=user.department),
            Q(transactor=user))

    def attach_context(self, user, projects, schedules, pays, context):
        pay_value = pays.aggregate(Sum('amount'))['amount__sum'] or 0
        projectnum = projects.count
        projectfin = projects.filter(task_state=u'完成').count
        projectufin = projects.exclude(task_state=u'完成').count

        tasknum = schedules.count
        taskfin = schedules.filter(isfin=True).count
        taskufin = schedules.filter(isfin=False).count

        paynum = pays.count

        projects = projects[:5]
        schedules = schedules[:5]
        pays = pays[:5]

        context['touser'] = user
        context['paynum'] = paynum
        context['pay_value'] = pay_value
        context['projectnum'] = projectnum
        context['projectfin'] = projectfin
        context['projectufin'] = projectufin
        context['schedulenum'] = tasknum
        context['schedulefin'] = taskfin
        context['scheduleufin'] = taskufin

        context['projects'] = projects
        context['schedules'] = schedules
        context['pays'] = pays

        cprogresses = {}
        for cproject in projects:
            cprogresses[cproject.id] = cproject.progress()
        context['cprogresses'] = cprogresses

        sexpireds = {}
        for schedule in schedules:
            sexpireds[schedule.id] = schedule.is_expired()
        context['sexpireds'] = sexpireds
        return context

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # -1 则默认为查看自己的看板数据
        u_id = self.kwargs.get('u_id', -1)
        user = self.request.user if u_id < 0 else User.objects.get(pk=u_id)
        if not user:
            return context

        projects = self.get_projects(user)
        schedules = self.get_schedules(user)
        pays = self.get_pays(user)

        context = self.attach_context(user, projects, schedules, pays, context)

        return context


class DepmentKanbanView(PersonKanbanView):
    template_name = 'kanban/depment.html'

    def get_projects(self, user: User):
        return Project.objects.filter(department=user.department)

    def get_schedules(self, user: User):
        return Schedule.objects.filter(department=user.department)

    def get_pays(self, user: User):
        return Pay.objects.filter(department=user.department)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        user = self.request.user
        projects = self.get_projects(user)
        schedules = self.get_schedules(user)
        pays = self.get_pays(user)

        projects = self.get_projects(user)
        schedules = self.get_schedules(user)
        pays = self.get_pays(user)

        context = self.attach_context(user, projects, schedules, pays, context)
        return context

templates/kanban/depment.html
{% extends "base.html" %}
{% load static %}
{% load getitem_tag %}

{% block content %}
<div class="container-xl">
    <!-- Page title -->
    <div class="page-header d-print-none">
      <div class="row align-items-center">
        <div class="row">
          <h2 class="page-title">
            部门看板——{{ touser.department }}
          </h2>
        </div>
      </div>
    </div>
    <div class="page-body">
        <div class="container-xl">
        <!-- Page title actions -->
    <div class="row row-deck row-cards">
            <div class="col-sm-3 col-lg-4">
              {% include "kanban/project_card_comp.html" %}
            </div>

            <div class="col-sm-3 col-lg-4">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex align-items-center">
            
                    <div class="h1">
                      任务
                    </div>
                  </div>
                  <div class="h2 mb-3">所有：{{ schedulenum }}</div>
                  <div class="h3 mb-3">完成：{{ schedulefin }}</div>
                  <div class="h3 mb-3">未完成：{{ scheduleufin }}</div>
                  
                </div>
                <div id="chart1" class="chart-sm mt-3" style="min-height: 80px;"></div>
              </div>
            </div>

            <div class="col-sm-3 col-lg-4">
              {% include "kanban/pays_card_comp.html" %}
            </div>
    

</div>
</div>
</div>
  </div>

{% endblock %}

{% block addjs %}
<script src="{% static 'plugins/echarts/echarts.min.js' %}"></script>
<script type="text/javascript">
var myChart = echarts.init(document.getElementById('chart1'));
$.ajax({
  type: "get",
  async: true,
  url:  '{% url 'load_tasks_dayfin_dep' %}?day=7',
  dataType: "json",
  success: function(data){
    if(data){
      option = {
        xAxis: {
          type: 'category',
          data: []
        },
        yAxis: {
          type: 'value',
          minInterval: 3
        },
        series: [
        {
          data: data.series,
          type: 'line'
        }
        ]
      }
      myChart.setOption(option);
    }
  }
})


</script>
{% endblock %}

templates/kanban/pays_card_comp.html
{% load getitem_tag %}

<div class="card">
    <div class="card-body">
      <div class="d-flex align-items-center">

        <div class="h1">
          费用
        </div>
      </div>
      <div class="h2 mb-3">数量：{{ paynum }}</div>
      <div class="h3 mb-3"></div>
      <div class="h3 mb-3">总额：{{ pay_value|div:10000 }}万</div>
    </div>
</div>

templates/kanban/personto.html
{% extends "base.html" %}
{% load static %}
{% load getitem_tag %}

{% block content %}
<div class="container-xl">
    <!-- Page title -->
    <div class="page-header d-print-none">
      <div class="row align-items-center">
        <div class="row">
          <h2 class="page-title">
            个人看板——{{ touser.realname }}
          </h2>
        </div>
      </div>
    </div>
    <div class="page-body">
        <div class="container-xl">
        <!-- Page title actions -->
    <div class="row row-deck row-cards">
            <div class="col-sm-3 col-lg-4">
                <div class="card">
                  <div class="card-body">
                    <div class="d-flex align-items-center">

                      <div class="h1">
                        项目
                      </div>
                    </div>
                    <div class="h2 mb-3">所有：{{ projectnum }}</div>
                    <div class="h3 mb-3">完成：{{ projectfin }}</div>
                    <div class="h3 mb-3">未完成：{{ projectufin }}</div>
                  </div>
                </div>
            </div>

            <div class="col-sm-3 col-lg-4">
                <div class="card">
                  <div class="card-body">
                    <div class="d-flex align-items-center">

                      <div class="h1">
                        任务
                      </div>
                    </div>
                    <div class="h2 mb-3">所有：{{ schedulenum }}</div>
                    <div class="h3 mb-3">完成：{{ schedulefin }}</div>
                    <div class="h3 mb-3">未完成：{{ scheduleufin }}</div>
                    
                  </div>
                  <div id="chart1" class="chart-sm" style="min-height: 80px;"></div>
                </div>
            </div>

            <div class="col-sm-3 col-lg-4">
                <div class="card">
                  <div class="card-body">
                    <div class="d-flex align-items-center">

                      <div class="h1">
                        费用
                      </div>
                    </div>
                    <div class="h2 mb-3">数量：{{ paynum }}</div>
                    <div class="h3 mb-3"></div>
                    <div class="h3 mb-3">总额：{{ pay_value|div:10000 }}万</div>
                  </div>
                </div>
            </div>
    

    <div class="col-md-5 col-lg-6">
        <div class="card">
            <div class="card-header">
              <h3 class="card-title">项目</h3>
              <div class="col-md-2 ml-auto"><a href="{% url 'project_list' %}">更多</a></div>
            </div>
            <div class="table-responsive">
              <table class="table table-sm card-table table-vcenter">
                  <thead>
                      <tr>
                          <th scope="col">项目</th>
                          <th scope="col">进度</th>
                          <th scope="col"></th>
                      </tr>
                  </thead>
                  <tbody>
                      {% for project in projects %}
                      <tr>
                        <td><a href="{% url 'project_detail' project.id%}">{{ project.name }}</a></td>
                        <td>
                            <progress max="100" value="{{ progresses|get_item:project.id }}"></progress></td>
                            <td><a href="{% url 'project_update' project.id%}">编辑</a></td>
                      </tr>
              {% endfor %}
                  </tbody>
              </table>
            </div>
          </div>
    </div>

    <div class="col-md-5 col-lg-6">
        <div class="card">
            <div class="card-header">
              <h3 class="card-title">费用</h3>
              <div class="col-md-2 ml-auto"><a href="{% url 'pay_list' %}">更多</a></div>
            </div>
            <div class="table-responsive">
              <table class="table card-table table-vcenter">
                  <thead>
                      <tr>
                          <th scope="col">费用</th>
                          <th scope="col">项目</th>
                          <th scope="col">时间</th>
                          <th scope="col">金额</th>
                          <th scope="col"></th>
                      </tr>
                  </thead>
                  <tbody>
                      {% for pay in pays %}
                      <tr>
                        <td>{{ pay.name }}</td>
                        <td>{{ pay.project.name }}</td>
                        <td>{{ pay.paydate }}</td>
                        <td>{{ pay.amount }}</td>
                        <td><a href="{% url 'pay_update' pay.id%}">编辑</a></td>
                      </tr>
              {% endfor %}
                  </tbody>
              </table>
            </div>
          </div>
    </div>

    <div class="col-md-10 col-lg-12">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">任务</h3>
            <div class="col-md-2 ml-auto"><a href="{% url 'schedule_list' %}">更多</a></div>
          </div>
          <div class="table-responsive">
            <table class="table card-table table-vcenter">
                <thead>
                    <tr>
                        <th scope="col">事项</th>
                        <th scope="col">项目</th>
                        <th scope="col">是否完成</th>
                        <th scope="col">截止时间</th>
                        <th scope="col">超期否</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for schedule in schedules %}
                    <tr>
                        <td><a href="{% url 'schedule_detail' schedule.id%}">{{ schedule.name }}</a></td>
                        <td><a href="{% url 'project_detail' schedule.project.id%}">{{ schedule.project.name }}</a></td>
                        <td><input type="checkbox" onclick="return false" {% if schedule.isfin %}checked{% endif %} /></td>
                        <td>{{ schedule.deadline|date:"Y年m月d日" }}</td>
                        <td>{% if sexpireds|get_item:schedule.id %}<span class="badge bg-danger">超期</span>
                        {% else %}<span class="badge bg-success">未超期</span>{% endif %}</td>
                        <td><a href="{% url 'schedule_update' schedule.id%}">修改</a></td>
                    </tr>
            {% endfor %}
                </tbody>
            </table>
          </div>
        </div>
    </div>
</div>
</div>
</div>
  </div>

{% endblock %}

{% block addjs %}
<script src="{% static 'plugins/echarts/echarts.min.js' %}"></script>
<script type="text/javascript">
var myChart = echarts.init(document.getElementById('chart1'));
$.ajax({
  type: "get",
  async: true,
  url:  '{% url 'load_tasks_dayfin' %}/{{ touser.id }}?day=7',
  dataType: "json",
  success: function(data){
    if(data){
      option = {
        xAxis: {
          type: 'category',
          data: []
        },
        yAxis: {
          type: 'value',
          minInterval: 3
        },
        series: [
        {
          data: data.series,
          type: 'line'
        }
        ]
      }
      myChart.setOption(option);
    }
  }
})


</script>
{% endblock %}

templates/kanban/project_card_comp.html
<div class="card">
    <div class="card-body">
      <div class="d-flex align-items-center">

        <div class="h1">
          项目
        </div>
      </div>
      <div class="h2 mb-3">所有：{{ projectnum }}</div>
      <div class="h3 mb-3">完成：{{ projectfin }}</div>
      <div class="h3 mb-3">未完成：{{ projectufin }}</div>
    </div>
  </div>

templates/kanban/schedule_card_comp.html
{% load static %}

<div class="card">
    <div class="card-body">
      <div class="d-flex align-items-center">

        <div class="h1">
          任务
        </div>
      </div>
      <div class="h2 mb-3">所有：{{ schedulenum }}</div>
      <div class="h3 mb-3">完成：{{ schedulefin }}</div>
      <div class="h3 mb-3">未完成：{{ scheduleufin }}</div>
      
    </div>
    <div id="chart1" class="chart-sm mt-3" style="width:400px;min-height: 80px;"></div>
  </div>

  <script src="{% static 'plugins/echarts/echarts.min.js' %}"></script>
  <script type="text/javascript">
  var myChart = echarts.init(document.getElementById('chart1'));
  $.ajax({
    type: "get",
    async: true,
    url:  '{% url 'load_tasks_dayfin' %}?day=7',
    dataType: "json",
    success: function(data){
      if(data){
        option = {
          xAxis: {
            type: 'category',
            data: []
          },
          yAxis: {
            type: 'value',
            minInterval: 3
          },
          series: [
          {
            data: data.series,
            type: 'line'
          }
          ]
        }
        myChart.setOption(option);
      }
    }
  })
  </script>